[project]
name = "serving"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flash-attn>=2.8.3",
    "torch==2.8.0",
    "torchao==0.13.0",
    "torchvision==0.23.0",
    "vllm==0.11.0",
]
